GENERAL:
  IMAGE: grafana/grafana
  TAG: latest
  NAME: grafana

NETWORK_CONFIGS:
  NETWORK_MODE: ports
  PORTS:
    - 3000

ENV_VARS:
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: passwd
  GF_AUTH_DISABLE_LOGIN_FORM: false
  GF_AUTH_ANONYMOUS_ENABLED: true
  GF_SECURITY_ALLOW_EMBEDDING: true
  GF_INSTALL_PLUGINS: "simpod-json-datasource,grafana-worldmap-panel"

VOLUMES:
  grafana-data: /var/lib/grafana
  grafana-log: /var/log/grafana
  grafana-config: /etc/grafana