metadata:
  # Kubernetes Instance namespace
  namespace: default
  # hostname for deployment
  hostname: nginx-node
  # deployment application name
  app_name: nginx
  # Pod application name
  pod_name: nginx-node-pod
  # Kubernetes deployment name
  deployment_name: nginx-node-deployment
  # Kubernetes service name
  service_name: nginx-node-service
  # Configuration mapping name
  configmap_name: nginx-node-configmap
  # Allows running Kubernetes remotely. If commented out, code will ignore it
  node_selector: ""
  # Number of Kubernetes replicas
  replicas: 1

image:
  # (Docker Hub) Image Path
  repository: nginx

node_configs:
  kubernetes:
    ip: 192.168.49.2
  nginx:
    nginx_port: 80
    node_port: 30800
  networking:
    # Port address used by AnyLog's TCP protocol to communicate with other nodes in the network
    ANYLOG_SERVER_PORT: 32458
    # Port address used by AnyLog's REST protocol
    ANYLOG_REST_PORT: 32459
    # Port value to be used as an MQTT broker, or some other third-party broker
    ANYLOG_BROKER_PORT: ""

