FROM python:3.13-slim

WORKDIR /app

COPY requirements.license_server.txt .
RUN pip install --no-cache-dir -r requirements.license_server.txt

COPY license-server.py app.py

RUN mkdir -p /data

EXPOSE 8001

CMD ["gunicorn", "--bind", "0.0.0.0:8001", "--workers", "2", "--access-logfile", "-", "--error-logfile", "-", "app:app"]