#version: "3"
services:
  remote-cli:
    image: anylogco/remote-cli:latest
    container_name: remote-cli
    restart: always
    stdin_open: true
    tty: true
    network_mode: bridge
    ports:
      - 31800:31800
    environment:
      - CONN_IP=0.0.0.0
      - CLI_PORT=31800
    volumes:
      - remote-cli:/app/Remote-CLI/djangoProject/static/json
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
  anylog-query:
    image: anylogco/anylog-network:1.3.2405
    restart: always
    env_file:
      -  ../docker-makefile/query-configs/base_configs.env
      - ../docker-makefile/query-configs/advance_configs.env
      - ../docker-makefile/.env
    container_name: anylog-query
    stdin_open: true
    tty: true
    network_mode: bridge
    ports:
      - 32348:32348
      - 32349:32349
    volumes:
      - anylog-query-anylog:/app/AnyLog-Network/anylog
      - anylog-query-blockchain:/app/AnyLog-Network/blockchain
      - anylog-query-data:/app/AnyLog-Network/data
      - anylog-query-local-scripts:/app/deployment-scripts
      - anylog-query-nebula:/app/AnyLog-Network/nebula
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
volumes:
  anylog-query-anylog:
  anylog-query-blockchain:
  anylog-query-data:
  anylog-query-local-scripts:
  anylog-query-nebula:
  remote-cli:
  remote-cli-current: