version: '3.3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-docker
    restart: always

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    ports:
      - "27071:27017"   # HOST:CONTAINER

    volumes:
      - type: volume
        source: mongo-data
        target: /data/db

      - type: volume
        source: mongo-configs
        target: /data/configdb

volumes:
  mongo-data:
  mongo-configs:

