[metadata]
name = docker-compose
version = 2.1.2609 (os-dev - 788292 [2026-09-23 16:26:05])
author = AnyLog Co.
contact = info@anylog.co
description = docker-compose configurations for AnyLog deployment
license = Copyright AnyLog Co.
site = https://anylog.co
docs = https://github.com/AnyLog-co/documentation
source = https://github.com/AnyLog-co
