[metadata]
name = docker-compose
version = 1.5.2604 (main - 4051d8 [2026-09-01 17:03:54])
author = AnyLog Co.
contact = info@anylog.co
description = docker-compose configurations for AnyLog deployment
license = Copyright AnyLog Co.
site = https://anylog.co
docs = https://github.com/AnyLog-co/documentation
source = https://github.com/AnyLog-co
