#!/usr/bin/env bash

# -------- Helpers --------
die() {
  echo "Error: $1" >&2
  exit "${2:-1}"
}

OS_TYPE=$(uname -s)

# WSL reports uname -s as Linux; detect it for compose template auto-selection.
_is_wsl() {
  if [[ -n "${WSL_DISTRO_NAME:-}" ]]; then
    return 0
  fi
  if grep -qiE 'microsoft|wsl' /proc/version 2>/dev/null; then
    return 0
  fi
  return 1
}

# Auto-select ports-based compose on WSL, macOS, and other non-native-Linux hosts.
_auto_use_ports_template() {
  if [[ "${OS_TYPE}" == "Darwin" ]]; then
    return 0
  fi
  if _is_wsl; then
    return 0
  fi
  if [[ "${OS_TYPE}" != "Linux" ]]; then
    return 0
  fi
  return 1
}

if [[ "$OS_TYPE" == "Darwin" ]]; then
  SED_INPLACE="sed -i .bak"
else
  SED_INPLACE="sed -i.bak"
fi

# -------- Args --------
NODE_CONFIGS=${1:-anylog-generic}
TAG=${2:-latest}
DEPLOYMENT_TYPE=${3:-docker}
export TAG

if [[ "${DEPLOYMENT_TYPE}" == "k8s" ]]; then
  die "k8s deployment not yet supported"
fi

# -------- Locate Config File --------
SOURCE_FILE="docker-makefiles/${NODE_CONFIGS}/node_configs.env"
ENV_FILE="docker-makefiles/${NODE_CONFIGS}/formatted_node_configs.env"

[[ -f "${SOURCE_FILE}" ]] || die "Missing configuration file: ${SOURCE_FILE}"

# -------- Generate Snapshot --------
bash docker-makefiles/prep_configs.sh "${NODE_CONFIGS}"

# -------- Load Configs --------
export NETWORK_TYPE=$(grep -m1 '^NETWORK_TYPE=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
export IMAGE=$(grep -m1 '^IMAGE=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
export ENABLE_REMOTE_GUI=$(grep -m1 '^ENABLE_REMOTE_GUI=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')

# -------- Load Configs (Node Naming) --------
NODE_NAME=$(grep -m1 '^NODE_NAME=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
CONTAINER_NAME=$(grep -m1 '^CONTAINER_NAME=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
NODE_TYPE=$(grep -m1 '^NODE_TYPE=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
COMPANY_NAME=$(grep -m1 '^COMPANY_NAME=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
CLUSTER_NAME=$(grep -m1 '^CLUSTER_NAME=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')

SYNC_SOURCE="false"   # did we have to fill in/derive a value?
SYNC_CLUSTER="false"  # did we have to fill in/derive cluster?

if [[ -n "${CONTAINER_NAME}" && -z "${NODE_NAME}" ]]; then
  # CONTAINER_NAME set, NODE_NAME missing -> mirror it
  # NODE_NAME is only mirrored in memory (not written to the config), so this is informational.
  NODE_NAME="${CONTAINER_NAME}"
  printf "# Info: NODE_NAME not set; using CONTAINER_NAME (\"%s\") for this build.\n" "${CONTAINER_NAME}" >&2
elif [[ -n "${NODE_NAME}" && -z "${CONTAINER_NAME}" ]]; then
  # NODE_NAME set, CONTAINER_NAME missing -> mirror it
  CONTAINER_NAME="${NODE_NAME}"
  SYNC_SOURCE="true"
  printf "\n# Warning: CONTAINER_NAME was missing; setting it to match NODE_NAME (\"${NODE_NAME}\") in ${SOURCE_FILE}.\n" >&2
elif [[ -z "${NODE_NAME}" && -z "${CONTAINER_NAME}" ]]; then
  # Neither set -> generate: ${NODE_TYPE}-${COMPANY_NAME-${HOSTNAME}}-${RANDOM}
  NAME_HOST="${COMPANY_NAME:-$(hostname)}"
  GENERATED_NAME="${NODE_TYPE}-${NAME_HOST}-${RANDOM}"
  NODE_NAME="${GENERATED_NAME}"
  CONTAINER_NAME="${GENERATED_NAME}"
  SYNC_SOURCE="true"
  printf "\n# Warning: NODE_NAME and CONTAINER_NAME were both missing; generated \"${GENERATED_NAME}\" and wrote it to ${SOURCE_FILE}.\n" >&2
fi
# else: both already set (and possibly different) -> leave as-is

#if [[ -z ${CLUSTER_NAME} ]] ; then
#  CLUSTER_NAME="cluster-${NODE_NAME}"
#  SYNC_CLUSTER="true"
#fi


export CONTAINER_NAME
export NODE_NAME
export CLUSTER_NAME

# Always keep the formatted/working copy in sync
${SED_INPLACE} "s/^#\{0,1\}CONTAINER_NAME=.*/CONTAINER_NAME=\"${CONTAINER_NAME}\"/g" "${ENV_FILE}"
#${SED_INPLACE} "s/^#\{0,1\}NODE_NAME=.*/NODE_NAME=\"${NODE_NAME}\"/g" "${ENV_FILE}"
#${SED_INPLACE} "s/^#\{0,1\}CLUSTER_NAME=.*/CLUSTER_NAME=\"${CLUSTER_NAME}\"/g" "${ENV_FILE}"

# If we had to invent/mirror a value, persist it back to the ORIGINAL
# source file too (with a warning), so a `clean`/regen from node_configs.env
# doesn't silently lose the name we assigned and generate a new random one.
if [[ "${SYNC_SOURCE}" == "true" ]]; then
  if ! grep -q '^# WARNING: NODE_NAME/CONTAINER_NAME auto-synced' "${SOURCE_FILE}"; then
    printf '\n# WARNING: NODE_NAME/CONTAINER_NAME auto-synced/generated by build_docker_compose.sh.\n# Deleting these lines will cause a new name to be generated on the next build.\n' >> "${SOURCE_FILE}"
  fi

  if grep -q '^#\{0,1\}CONTAINER_NAME=' "${SOURCE_FILE}"; then
    ${SED_INPLACE} "s/^#\{0,1\}CONTAINER_NAME=.*/CONTAINER_NAME=${CONTAINER_NAME}/g" "${SOURCE_FILE}"
  else
    printf 'CONTAINER_NAME="%s"\n' "${CONTAINER_NAME}" >> "${SOURCE_FILE}"
  fi

#  if grep -q '^#\{0,1\}NODE_NAME=' "${SOURCE_FILE}"; then
#    ${SED_INPLACE} "s/^#\{0,1\}NODE_NAME=.*/NODE_NAME=${NODE_NAME}/g" "${SOURCE_FILE}"
#  else
#    printf 'NODE_NAME="%s"\n' "${NODE_NAME}" >> "${SOURCE_FILE}"
#  fi
fi

if [[ "${SYNC_CLUSTER}" == "true" ]]; then
  echo "Warning: CLUSTER_NAME was missing; generated \"${CLUSTER_NAME}\" and wrote it to ${SOURCE_FILE}." >&2

#  if ! grep -q '^# WARNING: CLUSTER_NAME auto-generated' "${SOURCE_FILE}"; then
#    printf '\n# WARNING: CLUSTER_NAME auto-generated by build_docker_compose.sh.\n# Deleting this line will cause a new cluster name to be generated on the next build.\n' >> "${SOURCE_FILE}"
#  fi
#
#  if grep -q '^#\{0,1\}CLUSTER_NAME=' "${SOURCE_FILE}"; then
#    ${SED_INPLACE} "s/^#\{0,1\}CLUSTER_NAME=.*/CLUSTER_NAME=${CLUSTER_NAME}/g" "${SOURCE_FILE}"
#  else
#    printf 'CLUSTER_NAME="%s"\n' "${CLUSTER_NAME}" >> "${SOURCE_FILE}"
#  fi
fi

# Comment out remaining empty-value vars so they are not passed to the container
${SED_INPLACE} -E 's/^([A-Za-z_][A-Za-z0-9_]*)=""(\s*(#.*)?)$/#\1=""\2/' "${ENV_FILE}"

export ANYLOG_SERVER_PORT=$(grep -m1 '^ANYLOG_SERVER_PORT=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
export ANYLOG_REST_PORT=$(grep -m1 '^ANYLOG_REST_PORT=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
export ANYLOG_BROKER_PORT=$(grep -m1 '^ANYLOG_BROKER_PORT=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
export DOCKER_SOCKET=$(grep -m1 '^DOCKER_SOCKET=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
export DEPLOYMENTS_REPO=$(grep -m1 '^DEPLOYMENTS_REPO=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
DEPLOYMENTS_BRANCH="${DEPLOYMENTS_BRANCH:-$(grep -m1 '^DEPLOYMENTS_BRANCH=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')}"
export DEPLOYMENTS_BRANCH
export USER_VOLUMES=$(grep -m1 '^USER_VOLUMES=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')

# -------- LICENSE_KEY: prefer env var (set by Makefile), fall back to config file --------
if [[ -z "${LICENSE_KEY:-}" ]]; then
  export LICENSE_KEY=$(grep -m1 '^LICENSE_KEY=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
fi

# -------- Select Template --------
COMPOSE_FILE="docker-makefiles/docker-compose-template.yaml"

if [[ -n "${NETWORK_TYPE}" ]] && [[ "${NETWORK_TYPE}" != "network" ]] && [[ "${NETWORK_TYPE}" != "ports" ]]; then
  TEMPLATE_COMPOSE_FILE="docker-makefiles/docker-compose-template-specific-base.yaml"
elif [[ "${NETWORK_TYPE}" == "ports" ]]; then
  TEMPLATE_COMPOSE_FILE="docker-makefiles/docker-compose-template-ports-base.yaml"
elif [[ "${NETWORK_TYPE}" == "network" ]]; then
  TEMPLATE_COMPOSE_FILE="docker-makefiles/docker-compose-template-base.yaml"
elif [[ -z "${NETWORK_TYPE}" ]] && _auto_use_ports_template; then
  TEMPLATE_COMPOSE_FILE="docker-makefiles/docker-compose-template-ports-base.yaml"
else
  TEMPLATE_COMPOSE_FILE="docker-makefiles/docker-compose-template-base.yaml"
fi

[[ -f "$TEMPLATE_COMPOSE_FILE" ]] || die "$TEMPLATE_COMPOSE_FILE not found"
cp "$TEMPLATE_COMPOSE_FILE" "${COMPOSE_FILE}"

# -------- Inject env_file --------
awk -v cfg="../../docker-makefiles/${NODE_CONFIGS}/formatted_node_configs.env" \
    '/    env_file:/ {print; print "      - " cfg; next}1' \
    "${COMPOSE_FILE}" > temp.yaml && mv temp.yaml "${COMPOSE_FILE}"

# -------- Inject Broker Port --------
if [[ "${TEMPLATE_COMPOSE_FILE}" == *"ports"* ]] && [[ "${ANYLOG_BROKER_PORT}" =~ ^[0-9]+$ ]]; then
  awk -v port="${ANYLOG_BROKER_PORT}:${ANYLOG_BROKER_PORT}" \
      '/    ports:/ {print; print "      - " port; next}1' \
      "${COMPOSE_FILE}" > temp.yaml && mv temp.yaml "${COMPOSE_FILE}"
fi

# -------- Remove unresolved placeholders --------
# If ANYLOG_BROKER_PORT is not a valid port number, remove its placeholder
# line from the template so envsubst doesn't produce an invalid "- :" entry.
if [[ ! "${ANYLOG_BROKER_PORT:-}" =~ ^[0-9]+$ ]]; then
  ${SED_INPLACE} '/\${ANYLOG_BROKER_PORT}/d' "${COMPOSE_FILE}"
fi

# -------- Debug Sidecar (netshoot) --------
# Strip any debug service already in the template (active or commented-out copies),
# then add exactly one when DEBUG=true in node_configs.env.
DEBUG="$(grep -m1 '^DEBUG=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r' | tr '[:upper:]' '[:lower:]')"
DEBUG="${DEBUG:-false}"

awk '
  /^#?  \$\{CONTAINER_NAME\}-debug:[[:space:]]*$/ { skip=1; commented=($0 ~ /^#/); next }
  skip && commented  && /^#(#|    )/                                    { next }
  skip && !commented && (/^    / || /^##?    / || /^[[:space:]]*$/)     { next }
  { skip=0; print }
' "${COMPOSE_FILE}" > temp.yaml && mv temp.yaml "${COMPOSE_FILE}"

if [[ "${DEBUG}" == "true" ]]; then
  echo "Debug sidecar: enabled (${CONTAINER_NAME}-debug)"
  awk '
    /^volumes:/ && !done {
      print "  # netshoot: a container packed with network troubleshooting tools (tcpdump, dig, curl, iperf, nmap, etc.)."
      print "  # It shares the AnyLog container network namespace, so you can debug its networking without installing anything in it or on the host."
      print "  ${CONTAINER_NAME}-debug:"
      print "    image: nicolaka/netshoot"
      print "    container_name: ${CONTAINER_NAME}-debug"
      print "    network_mode: \"container:${CONTAINER_NAME}\""
      print "    stdin_open: true"
      print "    tty: true"
      print "    restart: \"no\""
      print "    depends_on:"
      print "      ${CONTAINER_NAME}:"
      print "        condition: service_started"
      done=1
    }
    { print }
  ' "${COMPOSE_FILE}" > temp.yaml && mv temp.yaml "${COMPOSE_FILE}"
else
  echo "Debug sidecar: disabled (set DEBUG=true in node_configs.env to enable)"
fi

# -------- Deployment Scripts Volume --------
# A local-scripts mount at /app/deployment-scripts is ALWAYS present:
#   - named volume ${CONTAINER_NAME}-local-scripts by default
#   - bind mount instead, only when DEPLOYMENTS_REPO is a local host directory
# Step 1: unconditionally enable the named volume (mount lines + top-level declaration),
#         whether the template ships them commented or not.
${SED_INPLACE} 's|^#\([[:space:]]*- \${CONTAINER_NAME}-local-scripts:/app/deployment-scripts\)|\1|' "${COMPOSE_FILE}"
${SED_INPLACE} 's|^#\(  \${CONTAINER_NAME}-local-scripts:\)[[:space:]]*$|\1|' "${COMPOSE_FILE}"

# Step 2: decide what fills it.
if [[ -z "${DEPLOYMENTS_REPO}" ]]; then
  # Option 1: built-in deployment-scripts from the image seed the named volume
  echo "Deployment scripts: built-in (named volume ${CONTAINER_NAME}-local-scripts)"
elif [[ -d "${DEPLOYMENTS_REPO}" ]]; then
  # Option 2: host directory -> bind mount replaces the named volume
  echo "Deployment scripts: host directory ${DEPLOYMENTS_REPO} (bind mount)"
  ${SED_INPLACE} "s|- \${CONTAINER_NAME}-local-scripts:/app/deployment-scripts|- ${DEPLOYMENTS_REPO}:/app/deployment-scripts|g" "${COMPOSE_FILE}"
  ${SED_INPLACE} "/^  \${CONTAINER_NAME}-local-scripts:[[:space:]]*$/d" "${COMPOSE_FILE}"
elif [[ "${DEPLOYMENTS_REPO}" == http://* || "${DEPLOYMENTS_REPO}" == https://* ]]; then
  # Option 3: git URL -> cloned at startup INTO the named volume (branch ${DEPLOYMENTS_BRANCH:-default})
  echo "Deployment scripts: git ${DEPLOYMENTS_REPO} @ ${DEPLOYMENTS_BRANCH:-default} (named volume ${CONTAINER_NAME}-local-scripts)"
else
  # Option 4: image reference -> helper container copies scripts into the named volume
  echo "Deployment scripts: image ${DEPLOYMENTS_REPO}:${DEPLOYMENTS_BRANCH} (named volume ${CONTAINER_NAME}-local-scripts)"
  awk -v repo="${DEPLOYMENTS_REPO}" \
      -v branch="${DEPLOYMENTS_BRANCH}" \
      -v node="${CONTAINER_NAME}" '
  /^services:/ {
    print;
    print "  " node "-deployment-scripts:";
    print "    image: " repo ":" branch;
    print "    container_name: " node "-deployment-scripts";
    print "    command: [\"sh\", \"-c\", \"cp -r /app/deployment-scripts/. /volume/\"]";
    print "    restart: \"no\"";
    print "    volumes:";
    print "      - " node "-local-scripts:/volume";
    next
  }1' "${COMPOSE_FILE}" > temp.yaml && mv temp.yaml "${COMPOSE_FILE}"
  ${SED_INPLACE} "s/condition: service_completed_successfully/condition: service_completed_successfully\n      ${CONTAINER_NAME}-deployment-scripts:\n        condition: service_completed_successfully/g" "${COMPOSE_FILE}"
fi

#----- Docker Sockets ----#
# -------- Docker Socket --------
if [[ -z "${DOCKER_SOCKET}" ]]; then
  if command -v docker >/dev/null 2>&1; then
    CONTEXT_SOCK=$(docker context inspect --format '{{.Endpoints.docker.Host}}' 2>/dev/null)
    CONTEXT_SOCK="${CONTEXT_SOCK#unix://}"

    if [[ "${CONTEXT_SOCK}" == *"/.colima/"* ]]; then
      # Colima's context path is a host-side forwarding socket, not a real
      # file inside the VM where the daemon actually runs. Bind-mounting it
      # into a container fails ("operation not supported") because the
      # daemon can't resolve that path in its own (VM) filesystem. The
      # daemon's real socket, as it sees it, is the standard guest path.
      DOCKER_SOCKET="/var/run/docker.sock"
    elif [[ -n "${CONTEXT_SOCK}" ]] && [[ -S "${CONTEXT_SOCK}" ]]; then
      DOCKER_SOCKET="${CONTEXT_SOCK}"
    fi
  fi
fi

# Fallback to common known paths if nothing resolved above
if [[ -z "${DOCKER_SOCKET}" ]]; then
  for candidate in \
    "/var/run/docker.sock" \
    "${XDG_RUNTIME_DIR:-}/docker.sock" \
    "${XDG_RUNTIME_DIR:-}/podman/podman.sock" \
    "${HOME}/.docker/run/docker.sock"
  do
    if [[ -n "${candidate}" ]] && [[ -S "${candidate}" ]]; then
      DOCKER_SOCKET="${candidate}"
      break
    fi
  done
fi
export DOCKER_SOCKET

if [[ -z "${DOCKER_SOCKET}" ]] || [[ ! -S "${DOCKER_SOCKET}" ]]; then
  awk '
    /^[[:space:]]*group_add:[[:space:]]*$/ {
      indent = $0; sub(/group_add:.*/, "", indent)
      print indent "#group_add:"
      getline nextline
      sub(/^[[:space:]]*/, "", nextline)
      print indent "  #" nextline
      next
    }
    { print }
  ' "${COMPOSE_FILE}" > temp.yaml && mv temp.yaml "${COMPOSE_FILE}"

  ${SED_INPLACE} "0,/- \${DOCKER_SOCKET}/s#- \${DOCKER_SOCKET}#\# - \${MISSING-DOCKER_SOCKET}#" "${COMPOSE_FILE}"
else
  if stat -c '%g' "${DOCKER_SOCKET}" >/dev/null 2>&1; then
    export DOCKER_GID=$(stat -c '%g' "${DOCKER_SOCKET}")
  else
    export DOCKER_GID=$(stat -f '%g' "${DOCKER_SOCKET}")
  fi
fi

# -------- Host Mounts --------
export HOST_PROC=$(grep -m1 '^HOST_PROC=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
export HOST_ROOT=$(grep -m1 '^HOST_ROOT=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
export HOST_SYS=$(grep -m1  '^HOST_SYS='  "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')

for VAR_NAME in HOST_PROC HOST_ROOT HOST_SYS; do
  HOST_PATH="${!VAR_NAME}"
  if [[ -z "${HOST_PATH}" ]] || [[ ! -e "${HOST_PATH}" ]]; then
    ${SED_INPLACE} "s|- \${${VAR_NAME}}:.*|# - \${MISSING-${VAR_NAME}}|g" "${COMPOSE_FILE}"
  fi
done

# -------- Remote-GUI --------
if [[ "${ENABLE_REMOTE_GUI}" == "true" ]]; then
  export REMOTE_GUI_NIC=$(grep -m1 '^REMOTE_GUI_NIC=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
  export REMOTE_GUI_FE=$(grep -m1 '^REMOTE_GUI_FE=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
  export REMOTE_GUI_BE=$(grep -m1 '^REMOTE_GUI_BE=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
  export REMOTE_GUI_TAG=$(grep -m1 '^REMOTE_GUI_TAG=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
  export GRAFANA_URL=$(grep -m1 '^GRAFANA_URL=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
#  export REMOTE_CONN=$(grep -m1 '^REMOTE_CONN=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')
  export OVERLAY_IP=$(grep -m1 '^OVERLAY_IP=' "$ENV_FILE" | cut -d= -f2- | tr -d '"\r')

  REMOTE_GUI_FE="${REMOTE_GUI_FE:-31800}"
  REMOTE_GUI_BE="${REMOTE_GUI_BE:-8080}"
  REMOTE_GUI_TAG="${REMOTE_GUI_TAG:-latest}"
  REMOTE_CONN="host.docker.internal:${ANYLOG_REST_PORT}"

  REMOTE_GUI_IP="127.0.0.1"
  if [[ -n "${REMOTE_GUI_NIC:-}" ]]; then
    if command -v ip >/dev/null 2>&1; then
      REMOTE_GUI_IP=$(ip -4 addr show dev "${REMOTE_GUI_NIC}" | awk '/inet /{print $2}' | cut -d/ -f1)
    elif command -v ifconfig >/dev/null 2>&1; then
      REMOTE_GUI_IP=$(ifconfig "${REMOTE_GUI_NIC}" | awk '/inet /{print $2}')
    fi
  fi

  if [[ ! -n "${REMOTE_CONN:-}" ]] && [[ -n "${OVERLAY_IP}" ]]; then
    export REMOTE_CONN="${OVERLAY_IP}:${ANYLOG_REST_PORT}"
  elif [[ ! -n "${REMOTE_CONN:-}" ]]; then
    export REMOTE_CONN="${REMOTE_GUI_IP}:${ANYLOG_REST_PORT}"
  fi

  awk -v vol1="image-vol:/app/CLI/local-cli-backend/static/" \
      -v vol2="usr-mgm-vol:/app/CLI/local-cli/backend/usr-mgm/" '
/    volumes:/ && !vol_found {
  print; print "      - " vol1; print "      - " vol2; vol_found=1; next
}1
END {
  print "  image-vol:"; print "  usr-mgm-vol:"; print "  report-configs:"; print "  backend-logs:"
}' "${COMPOSE_FILE}" > temp.yaml && mv temp.yaml "${COMPOSE_FILE}"

  awk -v remote_ip="$REMOTE_GUI_IP" \
      -v grafana="${GRAFANA_URL:-}" \
      -v fe_port="$REMOTE_GUI_FE" \
      -v be_port="$REMOTE_GUI_BE" \
      -v tag="$REMOTE_GUI_TAG" \
      -v remote_conn="${REMOTE_CONN}" '
/services:/ {
  print;
  print "  remote-gui:";
  print "    image: anylogco/remote-gui:" tag;
  print "    container_name: remote-gui";
  print "    hostname: remote-gui";
  print "    restart: always";
  print "    stdin_open: true";
  print "    tty: true";
  print "    ports:";
  print "      - " fe_port ":" fe_port;
  print "      - " be_port ":" be_port;
  print "    environment:";
  print "      - VITE_API_URL=http://" remote_ip ":" be_port;
  print "      - REMOTE_GUI_FE=" fe_port;
  print "      - REMOTE_GUI_BE=" be_port;
  print "      - REMOTE_CONN=" remote_conn;
  if (grafana != "") print "      - GRAFANA_URL=" grafana;
  print "    volumes:";
  print "      - image-vol:/app/CLI/local-cli-backend/static/";
  print "      - usr-mgm-vol:/app/CLI/local-cli/backend/usr-mgm/";
  print "      - report-configs:/app/CLI/local-cli-backend/plugins/reportgenerator/templates";
  print "      - backend-logs:/app/CLI/local-cli-backend/logs";
  next
}1' "${COMPOSE_FILE}" > temp.yaml && mv temp.yaml "${COMPOSE_FILE}"
fi

# -------- USER VOLUMES --------
if [[ -n "${USER_VOLUMES}" ]]; then
  VOLUME_INJECT=""
  for VOLUME in ${USER_VOLUMES}; do
    if [[ "${VOLUME}" == *"/"* ]]; then
      MOUNT_NAME=$(basename "${VOLUME}")
    elif [[ "${VOLUME}" == *"\\"* ]]; then
      MOUNT_NAME=$(echo "${VOLUME}" | awk -F "\\" '{print $NF}')
    else
      MOUNT_NAME="${VOLUME}"
    fi
    VOLUME_INJECT="${VOLUME_INJECT}\n      - ${VOLUME}:/app/${MOUNT_NAME}"
  done
  ${SED_INPLACE} "s#- \${CONTAINER_NAME}-data:/app/AnyLog-Network/data#- \${CONTAINER_NAME}-data:/app/AnyLog-Network/data${VOLUME_INJECT}#g" "${COMPOSE_FILE}"
fi

# -------- Envsubst & Write Output --------
echo "Generating final docker-compose.yaml..."
mkdir -p docker-makefiles/docker-compose-files
OUTPUT_FILE="docker-makefiles/docker-compose-files/${NODE_CONFIGS}-docker-compose.yaml"
envsubst < "${COMPOSE_FILE}" > "$OUTPUT_FILE"
rm -rf "${COMPOSE_FILE}" "${COMPOSE_FILE}.bak" docker-makefiles/${NODE_CONFIGS}/*.bak
echo "Saved: ${OUTPUT_FILE}"