services:
  remote-cli:
    image: anylogco/remote-cli:latest
    container_name: remote-cli
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 31800:31800
    environment:
      - CONN_IP=0.0.0.0
      - CLI_PORT=31800
    volumes:
      - remote-cli:/app/Remote-CLI/djangoProject/static/json
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
  anylog-node:
    image: anylogco/anylog-network:1.3.2501
    restart: always
    env_file:
      -  ../docker-makefiles/generic-configs/base_configs.env
      - ../docker-makefiles/generic-configs/advance_configs.env
      - .env
    container_name: anylog-node
    stdin_open: true
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    tty: true
    ports:
      - 4242:4242
      - 32550:32550
      - 32548:32548
      - 32549:32549
    volumes:
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
      - remote-cli:/app/Remote-CLI/djangoProject/static/json
      - nebula-overlay:/app/nebula
      - anylog-node-anylog:/app/AnyLog-Network/anylog
      - anylog-node-blockchain:/app/AnyLog-Network/blockchain
      - anylog-node-data:/app/AnyLog-Network/data
      - anylog-node-local-scripts:/app/deployment-scripts
volumes:
  anylog-node-anylog:
  anylog-node-blockchain:
  anylog-node-data:
  anylog-node-local-scripts:
  nebula-overlay:
  remote-cli:
  remote-cli-current:
