services:
  ${NODE_NAME}:
    image: ${IMAGE}:${TAG}
    restart: always
    env_file:
      -  ../docker-makefiles//${ANYLOG_TYPE}/base_configs.env
      - ../docker-makefiles/${ANYLOG_TYPE}/advance_configs.env
      - .env
    container_name: ${NODE_NAME}
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - ${NODE_NAME}-anylog:/app/${IMAGE_ROOT}/anylog
      - ${NODE_NAME}-blockchain:/app/${IMAGE_ROOT}/blockchain
      - ${NODE_NAME}-data:/app/${IMAGE_ROOT}/data
      - ${NODE_NAME}-local-scripts:/app/deployment-scripts
volumes:
  ${NODE_NAME}-anylog:
  ${NODE_NAME}-blockchain:
  ${NODE_NAME}-data:
  ${NODE_NAME}-local-scripts:
