version: "2.4"

services:
  ${NODE_NAME}:
    image: ${IMAGE}:${TAG}
    user: "root"
    pid: "host"
    group_add:
      - ${DOCKER_GID}
    platform: ${DOCKER_PLATFORM}
    restart: always
    env_file:
    container_name: ${NODE_NAME}
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - ${NODE_NAME}-anylog:/app/AnyLog-Network/anylog
      - ${NODE_NAME}-blockchain:/app/AnyLog-Network/blockchain
      - ${NODE_NAME}-data:/app/AnyLog-Network/data
      - ${NODE_NAME}-local-scripts:/app/deployment-scripts
      - ${DOCKER_SOCKET}:/var/run/docker.sock
      - /proc:/host_proc:ro
      - /:/host:ro
      - /sys:/host_sys:ro

volumes:
  ${NODE_NAME}-anylog:
  ${NODE_NAME}-blockchain:
  ${NODE_NAME}-data:
  ${NODE_NAME}-local-scripts: