services:
  ${CONTAINER_NAME}-init:
    image: busybox
    user: root
    group_add:
      - ${DOCKER_GID}
    restart: "no"
    command: [
      "sh", "-c",
      "chown -R 10001:10001
        /app/AnyLog-Network/anylog
        /app/AnyLog-Network/blockchain
        /app/AnyLog-Network/data
#        /app/AnyLog-Network/tpm
      "
    ]
    volumes:
      - ${CONTAINER_NAME}-anylog:/app/AnyLog-Network/anylog
      - ${CONTAINER_NAME}-blockchain:/app/AnyLog-Network/blockchain
      - ${CONTAINER_NAME}-data:/app/AnyLog-Network/data
#      - ${CONTAINER_NAME}-tpm:/app/AnyLog-Network/tpm_dir
      - ${CONTAINER_NAME}-local-scripts:/app/deployment-scripts
  ${CONTAINER_NAME}:
    image: ${IMAGE}:${TAG}
    user: root
    pid: "host"
    group_add:
      - ${DOCKER_GID}
    platform: ${DOCKER_PLATFORM}
    restart: always
    env_file:
    container_name: ${CONTAINER_NAME}
    stdin_open: true
    tty: true
    network_mode: host
    depends_on:
      ${CONTAINER_NAME}-init:
        condition: service_completed_successfully
    volumes:
      - ${CONTAINER_NAME}-anylog:/app/AnyLog-Network/anylog
      - ${CONTAINER_NAME}-blockchain:/app/AnyLog-Network/blockchain
      - ${CONTAINER_NAME}-data:/app/AnyLog-Network/data
#      - ${NODE_NAME}-tpm:/app/AnyLog-Network/tpm_diry
      - ${CONTAINER_NAME}-local-scripts:/app/deployment-scripts
      - ${DOCKER_SOCKET}:/var/run/docker.sock
      - /proc:/host_proc:ro
      - /:/host:ro
      - /sys:/host_sys:ro  # optional, useful for cgroup/disk info
volumes:
  ${CONTAINER_NAME}-anylog:
  ${CONTAINER_NAME}-blockchain:
  ${CONTAINER_NAME}-data:
#  ${CONTAINER_NAME}-tpm:
  ${CONTAINER_NAME}-local-scripts:
