services:
  remote-cli:
    image: anylogco/remote-cli:latest
    container_name: remote-cli
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 31800:31800
    environment:
      - CONN_IP=0.0.0.0
      - CLI_PORT=31800
    volumes:
      - remote-cli:/app/Remote-CLI/djangoProject/static/json
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
  ${NODE_NAME}:
    image: ${IMAGE}:${TAG}
    restart: always
    env_file:
      -  ../docker-makefiles/${ANYLOG_TYPE}-configs/base_configs.env
      - ../docker-makefiles/${ANYLOG_TYPE}-configs/advance_configs.env
      - .env
    container_name: ${NODE_NAME}
    stdin_open: true
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - NET_ADMIN
    tty: true
    ports:
      - 4242:4242
      - ${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}
      - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}
    volumes:
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
      - remote-cli:/app/Remote-CLI/djangoProject/static/json
      - nebula-overlay:/app/nebula
      - ${NODE_NAME}-anylog:/app/AnyLog-Network/anylog
      - ${NODE_NAME}-blockchain:/app/AnyLog-Network/blockchain
      - ${NODE_NAME}-data:/app/AnyLog-Network/data
      - ${NODE_NAME}-local-scripts:/app/deployment-scripts
volumes:
  ${NODE_NAME}-anylog:
  ${NODE_NAME}-blockchain:
  ${NODE_NAME}-data:
  ${NODE_NAME}-local-scripts:
  nebula-overlay:
  remote-cli:
  remote-cli-current:
