version: "2.2"
services:
  remote-cli:
    image: anylogco/remote-cli:latest
    container_name: remote-cli
    restart: always
    stdin_open: true
    tty: true
    ports:
      - ${CLI_PORT}:${CLI_PORT}
    environment:
      - CONN_IP=${CONN_IP}
      - CLI_PORT=${CLI_PORT}
    volumes:
      - remote-cli:/app/Remote-CLI/djangoProject/static/json
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
  anylog-query:
    image: anylogco/anylog-network:${TAG}
    env_file:
      - anylog_configs.env
      - advance_configs.env
    environment:
      - INIT_TYPE=${INIT_TYPE}
    container_name: ${CONTAINER_NAME}
    restart: always
    stdin_open: true
    tty: true
    ports:
      - ${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}
      - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}
    volumes:
      - anylog-query-anylog:/app/AnyLog-Network/anylog
      - anylog-query-blockchain:/app/AnyLog-Network/blockchain
      - anylog-query-data:/app/AnyLog-Network/data
      - anylog-query-local-scripts:/app/deployment-scripts
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
volumes:
  remote-cli:
  remote-cli-current:
  anylog-query-anylog:
  anylog-query-blockchain:
  anylog-query-data:
  anylog-query-local-scripts:
