services:
  remote-cli:
    image: anylogco/remote-cli:latest
    container_name: remote-cli
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 31800:31800
    environment:
      - CONN_IP=0.0.0.0
      - CLI_PORT=31800
    volumes:
      - remote-cli:/app/Remote-CLI/djangoProject/static/json
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
  anylog-${ANYLOG_TYPE}:
    image: anylogco/edgelake:${TAG}
    restart: always
    env_file:
      -  ../docker-makefile/${ANYLOG_PATH}/base_configs.env
      - ../docker-makefile/${ANYLOG_PATH}/advance_configs.env
      - .env
    container_name: anylog-${ANYLOG_TYPE}
    stdin_open: true
    tty: true
    network_mode: host
    cap_add:
      - NET_ADMIN  # Adding network administration capabilities for TUN device
    devices:
      - "/dev/net/tun:/dev/net/tun"  # Adding the TUN device to the container
    volumes:
      - anylog-${ANYLOG_TYPE}-anylog:/app/EdgeLake/anylog
      - anylog-${ANYLOG_TYPE}-blockchain:/app/EdgeLake/blockchain
      - anylog-${ANYLOG_TYPE}-data:/app/EdgeLake/data
      - anylog-${ANYLOG_TYPE}-local-scripts:/app/deployment-scripts
      - nebula-overlay:/app/nebula
      - remote-cli:/app/Remote-CLI/djangoProject/static/json
volumes:
  anylog-${ANYLOG_TYPE}-anylog:
  anylog-${ANYLOG_TYPE}-blockchain:
  anylog-${ANYLOG_TYPE}-data:
  anylog-${ANYLOG_TYPE}-local-scripts:
  remote-cli:
  remote-cli-current:
  nebula-overlay: