services:
  anylog-${ANYLOG_TYPE}:
    image: anylogco/anylog-network:${TAG}
    restart: always
    env_file:
      -  ../docker-makefile/${ANYLOG_TYPE}-configs/base_configs.env
      - ../docker-makefile/${ANYLOG_TYPE}-configs/advance_configs.env
      - .env
    container_name: anylog-${ANYLOG_TYPE}
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - anylog-${ANYLOG_TYPE}-anylog:/app/AnyLog-Network/anylog
      - anylog-${ANYLOG_TYPE}-blockchain:/app/AnyLog-Network/blockchain
      - anylog-${ANYLOG_TYPE}-data:/app/AnyLog-Network/data
      - anylog-${ANYLOG_TYPE}-local-scripts:/app/deployment-scripts
      - nebula-overlay:/app/nebula
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
volumes:
  anylog-${ANYLOG_TYPE}-anylog:
  anylog-${ANYLOG_TYPE}-blockchain:
  anylog-${ANYLOG_TYPE}-data:
  anylog-${ANYLOG_TYPE}-local-scripts:
  nebula-overlay:
  remote-cli:
  remote-cli-current:
