  services:
    anylog-${ANYLOG_TYPE}:
      image: ${IMAGE}:${TAG}
      restart: always
      env_file:
        -  ../docker-makefile/${ANYLOG_TYPE}-configs/base_configs.env
        - ../docker-makefile/${ANYLOG_TYPE}-configs/advance_configs.env
        - .env
      container_name: anylog-${ANYLOG_TYPE}
      stdin_open: true
      tty: true
    networks:
      nebula_network:
        aliases:
          - nebula  # Optional: add an alias for easier access
      ports:
        - ${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}
        - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}
        - 4242:4242/udp
      cap_add:
        - NET_ADMIN  # Adding network administration capabilities for TUN device
      devices:
        - "/dev/net/tun:/dev/net/tun"  # Adding the TUN device to the container
      volumes:
        - anylog-${ANYLOG_TYPE}-anylog:/app/AnyLog-Network/anylog
        - anylog-${ANYLOG_TYPE}-blockchain:/app/AnyLog-Network/blockchain
        - anylog-${ANYLOG_TYPE}-data:/app/AnyLog-Network/data
        - anylog-${ANYLOG_TYPE}-local-scripts:/app/deployment-scripts
        - nebula-overlay:/app/nebula
  volumes:
    anylog-${ANYLOG_TYPE}-anylog:
    anylog-${ANYLOG_TYPE}-blockchain:
    anylog-${ANYLOG_TYPE}-data:
    anylog-${ANYLOG_TYPE}-local-scripts:
    nebula-overlay:
networks:
  nebula_network:  # Define a custom bridge network
    driver: bridge
