#version: '3.8'  # Specify your Docker Compose version

networks:
  nebula-overlay:  # Define a custom overlay network
    driver: bridge  # Use overlay driver

services:
  anylog-${ANYLOG_TYPE}:
    image: ${IMAGE}:${TAG}
    restart: always
    env_file:
      - ../docker-makefile/${ANYLOG_TYPE}-configs/base_configs.env
      - ../docker-makefile/${ANYLOG_TYPE}-configs/advance_configs.env
      - .env
    container_name: anylog-${ANYLOG_TYPE}
    stdin_open: true
    tty: true
    ports:
      - ${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}  # Expose this specific port to the host
      - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}      # Expose this specific port to the host
      - 4242:4242/udp                               # UDP port mapping for Nebula or other services
    cap_add:
      - NET_ADMIN  # Adding network administration capabilities for TUN device
    devices:
      - "/dev/net/tun:/dev/net/tun"  # Adding the TUN device to the container
    volumes:
      - anylog-${ANYLOG_TYPE}-anylog:/app/AnyLog-Network/anylog
      - anylog-${ANYLOG_TYPE}-blockchain:/app/AnyLog-Network/blockchain
      - anylog-${ANYLOG_TYPE}-data:/app/AnyLog-Network/data
      - anylog-${ANYLOG_TYPE}-local-scripts:/app/deployment-scripts
      - nebula-overlay:/app/nebula
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
    networks:
      - nebula-overlay  # Attach to the custom overlay network

  remote-cli:
    image: anylogco/remote-cli:latest
    container_name: remote-cli
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 31800:31800  # Expose this specific port for CLI
    environment:
      - CONN_IP=0.0.0.0  # Allow connections from all interfaces
      - CLI_PORT=31800
    volumes:
      - remote-cli:/app/Remote-CLI/djangoProject/static/json
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
      - nebula-overlay:/app/nebula
    networks:
#      - cli-bridge  # Attach to the bridge network for external communication
      - nebula-overlay  # Attach to the overlay network for internal communication

volumes:
  anylog-${ANYLOG_TYPE}-anylog:
  anylog-${ANYLOG_TYPE}-blockchain:
  anylog-${ANYLOG_TYPE}-data:
  anylog-${ANYLOG_TYPE}-local-scripts:
  nebula-overlay:
  remote-cli:
  remote-cli-current:
