version: "3"
services:
#  remote-cli:
#    image: anylogco/remote-cli:latest
#    container_name: remote-cli
#    restart: always
#    stdin_open: true
#    tty: true
#    ports:
#      - ${CLI_PORT}:${CLI_PORT}
#    environment:
#      - CONN_IP=${CONN_IP}
#      - CLI_PORT=${CLI_PORT}
#    volumes:
#      - remote-cli:/app/Remote-CLI/djangoProject/static/json
#      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
  anylog-${ANYLOG_TYPE}:
    image: anylogco/anylog-network:${TAG}
    restart: always
    env_file:
      - ${ANYLOG_TYPE}-configs/base_configs.env
      - ${ANYLOG_TYPE}-configs/advance_configs.env
    environment:
      - INIT_TYPE=${INIT_TYPE}
    container_name: anylog-${ANYLOG_TYPE}
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - anylog-${ANYLOG_TYPE}-anylog:/app/AnyLog-Network/anylog
      - anylog-${ANYLOG_TYPE}-blockchain:/app/AnyLog-Network/blockchain
      - anylog-${ANYLOG_TYPE}-data:/app/AnyLog-Network/data
      - anylog-${ANYLOG_TYPE}-local-scripts:/app/deployment-scripts
      - anylog-${NODE_TYPE}-nebula:/app/AnyLog-Network/nebula
#      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
volumes:
  anylog-${ANYLOG_TYPE}-anylog:
  anylog-${ANYLOG_TYPE}-blockchain:
  anylog-${ANYLOG_TYPE}-data:
  anylog-${ANYLOG_TYPE}-local-scripts:
  anylog-${NODE_TYPE}-nebula:
#  remote-cli:
#  remote-cli-current: