version: '3.8'

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}  # Define a subnet that doesn't conflict with your host's network

services:
  anylog-${ANYLOG_TYPE}:
    image: ${IMAGE}:${TAG}
    restart: always
    env_file:
      -  ../docker-makefile/${ANYLOG_TYPE}-configs/base_configs.env
      - ../docker-makefile/${ANYLOG_TYPE}-configs/advance_configs.env
      - .env
    container_name: anylog-${ANYLOG_TYPE}
    stdin_open: true
    tty: true
    ports:
      - ${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}
      - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}
      - ${ANYLOG_BROKER_PORT}:${ANYLOG_BROKER_PORT}
    volumes:
      - anylog-${ANYLOG_TYPE}-anylog:/app/AnyLog-Network/anylog
      - anylog-${ANYLOG_TYPE}-blockchain:/app/AnyLog-Network/blockchain
      - anylog-${ANYLOG_TYPE}-data:/app/AnyLog-Network/data
      - anylog-${ANYLOG_TYPE}-local-scripts:/app/deployment-scripts
      - nebula-overlay:/app/nebula
    networks:
      custom_network:
        ipv4_address: ${IP_ADDR}  # Assign a static IP if needed

volumes:
  anylog-${ANYLOG_TYPE}-anylog:
  anylog-${ANYLOG_TYPE}-blockchain:
  anylog-${ANYLOG_TYPE}-data:
  anylog-${ANYLOG_TYPE}-local-scripts:
  nebula-overlay: