services:
  anylog-${ANYLOG_TYPE}:
    image: ${IMAGE}:${TAG}
    restart: always
    env_file:
      -  ../docker-makefile/${ANYLOG_TYPE}-configs/base_configs.env
      - ../docker-makefile/${ANYLOG_TYPE}-configs/advance_configs.env
      - .env
    container_name: anylog-${ANYLOG_TYPE}
    stdin_open: true
    tty: true
    ports:
      - ${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}
      - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}
      - ${ANYLOG_BROKER_PORT}:${ANYLOG_BROKER_PORT}
      - 4242:4242/udp
    cap_add:
      - NET_ADMIN  # Adding network administration capabilities for TUN device
    devices:
      - "/dev/net/tun:/dev/net/tun"  # Adding the TUN device to the container
    healthcheck:
      test: [ "CMD", "ping", "-c", "1", "${OVERLAY_IP}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - anylog-${ANYLOG_TYPE}-anylog:/app/AnyLog-Network/anylog
      - anylog-${ANYLOG_TYPE}-blockchain:/app/AnyLog-Network/blockchain
      - anylog-${ANYLOG_TYPE}-data:/app/AnyLog-Network/data
      - anylog-${ANYLOG_TYPE}-local-scripts:/app/deployment-scripts
      - nebula-overlay:/app/nebula
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
  remote-cli:
    image: anylogco/remote-cli:latest
    container_name: remote-cli
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 31800:31800
    environment:
      - CONN_IP=0.0.0.0
      - CLI_PORT=31800
    volumes:
      - remote-cli:/app/Remote-CLI/djangoProject/static/json
      - remote-cli-current:/app/Remote-CLI/djangoProject/static/blobs/current/
    depends_on:
      anylog-${ANYLOG_TYPE}:
        condition: service_healthy
volumes:
  anylog-${ANYLOG_TYPE}-anylog:
  anylog-${ANYLOG_TYPE}-blockchain:
  anylog-${ANYLOG_TYPE}-data:
  anylog-${ANYLOG_TYPE}-local-scripts:
  nebula-overlay:
  remote-cli:
  remote-cli-current:
