# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dados.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dados.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64\x61\x64os.proto\x12\x0bpersistence\" \n\x0cWatchRequest\x12\x10\n\x08table_id\x18\x01 \x01(\t\"\x17\n\x07\x44\x61taRow\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"\x1e\n\x0cReplyMessage\x12\x0e\n\x06Retval\x18\x01 \x01(\x05\x32U\n\x12PersistenceService\x12?\n\nWatchTable\x12\x19.persistence.WatchRequest\x1a\x14.persistence.DataRow0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dados_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WATCHREQUEST']._serialized_start=28
  _globals['_WATCHREQUEST']._serialized_end=60
  _globals['_DATAROW']._serialized_start=62
  _globals['_DATAROW']._serialized_end=85
  _globals['_REPLYMESSAGE']._serialized_start=87
  _globals['_REPLYMESSAGE']._serialized_end=117
  _globals['_PERSISTENCESERVICE']._serialized_start=119
  _globals['_PERSISTENCESERVICE']._serialized_end=204
# @@protoc_insertion_point(module_scope)
