version: "2.2"
services:
  postgres:
      image: postgres:14.0-alpine
      env_file:
        - postgres.env
      container_name: postgres
      restart: always
      stdin_open: true
      tty: true
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: