metadata:
  # Kubernetes Instance namespace
  namespace: default
  # hostname for deployment
  hostname: anylog-node
  # deployment application name
  app_name: anylog-node
  # Pod application name
  pod_name: anylog-node-pod

volume:
  anylog_volume:     # volume name: {.Values.metadata.deployment_name}-anylog-dir
    # Volume name associated with anylog directory
    volume_name: anylog-node-anylog-dir
    volume_name_pvc: anylog-node-anylog-dir-pvc
    # AnyLog security directory path
    path: /app/AnyLog-Network/anylog
    # Volume access mode
    access_mode: ReadWriteOnce
    # Volume storage size
    storage_size: 1Gi
  blockchain_volume:     # volume name: {.Values.metadata.deployment_name}-blockchain-dir
    # Volume name associated with blockchain directory
    volume_name: anylog-node-blockchain-dir
    volume_name_pvc: anylog-node-blockchain-dir-pvc
    # AnyLog blockchain directory path
    path: /app/AnyLog-Network/blockchain
    # Volume access mode
    access_mode: ReadWriteOnce
    # Volume storage size
    storage_size: 1Gi
  data_volume:     # volume name: {.Values.metadata.deployment_name}-data-dir
    # Volume name associated with data directory
    volume_name: anylog-node-data-dir
    volume_name_pvc: anylog-node-data-dir-pvc
    # AnyLog data directory path
    path: /app/AnyLog-Network/data
    # Volume access mode
    access_mode: ReadWriteOnce
    # Volume storage size
    storage_size: 1Gi
  local_scripts: # volume name: {.Values.metadata.deployment_name}-local-scripts
    # AnyLog local scripts directory path
    path: /app/deployment-scripts/node-deployment
    # Volume access mode
    access_mode: ReadWriteOnce
    # Volume storage size
    storage_size: 1Gi
  test_scripts: # volume name: {.Values.metadata.deployment_name}-tests
    # AnyLog test cases directory path
    path: /app/deployment-scripts/test
    # Volume access mode
    access_mode: ReadWriteOnce
    # Volume storage size
    storage_size: 1Gi