services:
  anylog-node-init:
    image: busybox
    user: root
    group_add:
      - 1001
    restart: "no"
    command: [
      "sh", "-c",
      "chown -R 10001:10001 
        /app/AnyLog-Network/anylog 
        /app/AnyLog-Network/blockchain 
        /app/AnyLog-Network/data 
        /app/deployment-scripts
      "
    ]
    volumes:
      - anylog-node-anylog:/app/AnyLog-Network/anylog
      - anylog-node-blockchain:/app/AnyLog-Network/blockchain
      - anylog-node-data:/app/AnyLog-Network/data
      - anylog-node-local-scripts:/app/deployment-scripts
  anylog-node:
    image: anylogco/anylog-network:1.4.2603-a99c5b
    user: "anylog:anylog"
    group_add:
      - 1001
    platform: linux/amd64
    restart: always
    env_file:
      - ../../docker-makefiles/anylog-generic/node_configs.env
    container_name: anylog-node
    stdin_open: true
    tty: true
    network_mode: host
    depends_on:
      anylog-node-init:
        condition: service_completed_successfully
    volumes:
      - anylog-node-anylog:/app/AnyLog-Network/anylog
      - anylog-node-blockchain:/app/AnyLog-Network/blockchain
      - anylog-node-data:/app/AnyLog-Network/data
      - anylog-node-local-scripts:/app/deployment-scripts
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  anylog-node-anylog:
  anylog-node-blockchain:
  anylog-node-data:
  anylog-node-local-scripts:
