metadata:
  # Kubernetes Instance namespace
  namespace: default
  # hostname for deployment
  hostname: anylog-node
  # deployment application name
  app_name: anylog-node
  # Pod application name
  pod_name: anylog-node-pod
  # Kubernetes deployment name
  deployment_name: anylog-node-deployment
  # Kubernetes service name
  service_name: anylog-node-service
  # Configuration mapping name
  configmap_name: anylog-node-configmap
  # Allows running Kubernetes remotely. If commented out, code will ignore it
  node_selector: ''
  # Number of Kubernetes replicas
  replicas: 1
image:
  # Image secret naming
  secret_name: imagepullsecret
  # (Docker Hub) Image Path
  repository: anylogco/anylog-network
  # Image version
  tag: 1.3.2404
  # Image pulling policy
  pull_policy: Always
  # whether to deploy AnyLog (prod) or a linux cli (bash) with AnyLog installed, but not running
  init_type: prod
