services:
  anylog-master:
    image: anylogco/anylog-network:1.4.2512
    user: ":"
    platform: linux/amd64
    restart: always
    env_file:
      -  ../../docker-makefiles/anylog-master/base_configs.env
      - ../../docker-makefiles/anylog-master/advance_configs.env
      - ../../docker-makefiles/anylog-master/.env
    container_name: anylog-master
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - anylog-master-anylog:/app/AnyLog-Network/anylog
      - anylog-master-blockchain:/app/AnyLog-Network/blockchain
      - anylog-master-data:/app/AnyLog-Network/data
      - anylog-master-local-scripts:/app/deployment-scripts
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  anylog-master-anylog:
  anylog-master-blockchain:
  anylog-master-data:
  anylog-master-local-scripts:
