services:
  edgex-operator1:
    image: anylogco/anylog-network:1.4.2510-beta8
    restart: always
    env_file:
      -  ../../docker-makefiles/edgex-operator1/base_configs.env
      - ../../docker-makefiles/edgex-operator1/advance_configs.env
      - ../../docker-makefiles/edgex-operator1/.env
    container_name: edgex-operator1
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - edgex-operator1-anylog:/app/AnyLog-Network/anylog
      - edgex-operator1-blockchain:/app/AnyLog-Network/blockchain
      - edgex-operator1-data:/app/AnyLog-Network/data
      - edgex-operator1-local-scripts:/app/deployment-scripts
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  edgex-operator1-anylog:
  edgex-operator1-blockchain:
  edgex-operator1-data:
  edgex-operator1-local-scripts:
