services:
  edgex-operator2:
    image: anylogco/anylog-network:1.4.2510-beta8
    restart: always
    env_file:
      -  ../../docker-makefiles/edgex-operator2/base_configs.env
      - ../../docker-makefiles/edgex-operator2/advance_configs.env
      - ../../docker-makefiles/edgex-operator2/.env
    container_name: edgex-operator2
    stdin_open: true
    tty: true
    network_mode: host
    volumes:
      - edgex-operator2-anylog:/app/AnyLog-Network/anylog
      - edgex-operator2-blockchain:/app/AnyLog-Network/blockchain
      - edgex-operator2-data:/app/AnyLog-Network/data
      - edgex-operator2-local-scripts:/app/deployment-scripts
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  edgex-operator2-anylog:
  edgex-operator2-blockchain:
  edgex-operator2-data:
  edgex-operator2-local-scripts:
