general:
  # AnyLog License Key
  LICENSE_KEY: ""
  # Information regarding which AnyLog node configurations to enable. By default, even if everything is disabled, AnyLog starts TCP and REST connection protocols
  NODE_TYPE: master
  # Name of the AnyLog instance
  NODE_NAME: anylog-master
  # Owner of the AnyLog instance
  COMPANY_NAME: New Company

networking:
  # Port address used by AnyLog's TCP protocol to communicate with other nodes in the network
  ANYLOG_SERVER_PORT: 32048
  # Port address used by AnyLog's REST protocol
  ANYLOG_REST_PORT: 32049
  # A bool value that determines if to bind to a specific IP and Port (a false value binds to all IPs)
  TCP_BIND: false
  # A bool value that determines if to bind to a specific IP and Port (a false value binds to all IPs)
  REST_BIND: false

database:
  # Physical database type (sqlite or psql)
  DB_TYPE: sqlite
  # Username for SQL database connection
  DB_USER: ""
  # Password correlated to database user
  DB_PASSWD: ""
  # Database IP address
  DB_IP: 127.0.0.1
  # Database port number
  DB_PORT: 5432
  # Whether to set autocommit data
  AUTOCOMMIT: false

blockchain:
  # TCP connection information for Master Node
  LEDGER_CONN: 127.0.0.1:32048

advance_settings:
  # Whether to automatically run a local (or personalized) script at the end of the process
  DEPLOY_LOCAL_SCRIPT: false
  # Deploy a process that accepts syslog - requires Message broker running
  DEPLOY_SYSLOG: false
  # Whether to monitor the node or not
  MONITOR_NODES: false
