metadata:
  # Kubernetes Instance namespace
  namespace: default
  # hostname for deployment
  hostname: anylog-operator
  # deployment application name
  app_name: anylog-operator
  # Pod application name
  pod_name: anylog-operator-pod
  # Kubernetes deployment name
  deployment_name: anylog-operator-deployment
  # Kubernetes service name
  service_name: anylog-operator-service
  # Configuration mapping name
  configmap_name: anylog-operator-configmap
  # Allows running Kubernetes remotely. If commented out, code will ignore it
  node_selector: ""
  # Number of Kubernetes replicas
  replicas: 1
image:
  # Image secret naming
  secret_name: imagepullsecret
  # (Docker Hub) Image Path
  repository: anylogco/anylog-network
  # Image version
  tag: test-arm64
  # Image pulling policy
  pull_policy: IfNotPresent
  # whether to deploy AnyLog (prod) or a linux cli (bash) with AnyLog installed, but not running
  init_type: prod

node_configs:
  general:
    # AnyLog License Key
    LICENSE_KEY: b7133573e398615da8fb419aedfa51af90307c9c3b1a2278561cf7e1040ade3b4a40cc8263724f9128de96198c13a447b1bd49b972f7e7bb37e6d3152d8ef139ed18514e6aa2038793e80068f586c12aee70718f43a5bfa901bf94844bf1a94087155f83c49980775518ace2de986af25ee2c5e5a0efc2833d16078aad9e28642024-02-01bGuest
    # Information regarding which AnyLog node configurations to enable. By default, even if everything is disabled, AnyLog starts TCP and REST connection protocols
    NODE_TYPE: operator
    # Name of the AnyLog instance
    NODE_NAME: anylog-operator
    # Owner of the Anylog instance
    COMPANY_NAME: New Company

  networking:
    # Port address used by AnyLog's TCP protocol to communicate with other nodes in the network
    ANYLOG_SERVER_PORT: 32148
    # Port address used by AnyLog's REST protocol
    ANYLOG_REST_PORT: 32149
    # Configurable (local) IP address that can be used when behind a proxy, or using Kubernetes for static IP
    PROXY_IP: 10.0.0.251
  database:
    # Physical database type
    DB_TYPE: sqlite
  blockchain:
    # TCP connection information for Master Node
    LEDGER_CONN: 10.0.0.251:32048
  operator:
    # Owner of the cluster
    CLUSTER_NAME: new-company-cluster1
    # Logical database name
    DEFAULT_DBMS: new_company
  mqtt:
    # Whether to enable the default MQTT process
    ENABLE_MQTT: true
  monitoring:
    # Whether to monitor the node or not
    MONITOR_NODES: true
    # Which node type to send monitoring information to
    MONITOR_NODE: query
    # Company node is associated with the monitor node
    MONITOR_NODE_COMPANY: New Company

volume:
  # Whether to enable volumes for AnyLog
  enable_volume: true
  anylog_volume: # volume name: {.Values.metadata.deployment_name}-anylog-dir
    # Volume name associated with anylog directory
    volume_name: anylog-operator-anylog-dir
    volume_name_pvc: anylog-operator-anylog-dir-pvc
  blockchain_volume: # volume name: {.Values.metadata.deployment_name}-blockchain-dir
    # Volume name associated with blockchain directory
    volume_name: anylog-operator-blockchain-dir
    volume_name_pvc: anylog-operator-blockchain-dir-pvc
  data_volume: # volume name: {.Values.metadata.deployment_name}-data-dir
    # Volume name associated with data directory
    volume_name: anylog-operator-data-dir
    volume_name_pvc: anylog-operator-data-dir-pvc
#  local_scripts: # volume name: {.Values.metadata.deployment_name}-local-scripts
#    # AnyLog local scripts directory path
#    path: /app/deployment-scripts/node-deployment
#    # Volume access mode
#    access_mode: ReadWriteOnce
#    # Volume storage size
#    storage_size: 1Gi
#  test_scripts: # volume name: {.Values.metadata.deployment_name}-tests
#    # AnyLog test cases directory path
#    path: /app/deployment-scripts/test
#    # Volume access mode
#    access_mode: ReadWriteOnce
#    # Volume storage size
#    storage_size: 1Gi

