apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{ .Values.metadata.namespace }}'
  name: '{{ .Values.metadata.configmap_name }}'
  labels:
    app: '{{ .Values.metadata.app_name }}'
data:
  # -- required params --

  # -- INIT Type --
  INIT_TYPE: '{{ .Values.image.init_type }}'
  DISABLE_CLI: '{{ .Values.image.disable_cli }}'

  # -- General --
  LICENSE_KEY: {{ .Values.node_configs.general.LICENSE_KEY }}
  NODE_TYPE: '{{ .Values.node_configs.general.NODE_TYPE }}'
  NODE_NAME: '{{ .Values.metadata.app_name }}'
  COMPANY_NAME: '{{ .Values.node_configs.general.COMPANY_NAME }}'

  # -- Networking --
  ANYLOG_SERVER_PORT: '{{ .Values.node_configs.networking.ANYLOG_SERVER_PORT }}'
  ANYLOG_REST_PORT: '{{ .Values.node_configs.networking.ANYLOG_REST_PORT }}'

  # -- blockchain --
  LEDGER_CONN: '{{ .Values.node_configs.blockchain.LEDGER_CONN }}'
