apiVersion: v1
kind: Service
metadata:
  namespace: '{{ .Metadata.metadata.namespace }}'
  name: '{{ .Metadata.metadata.service_name }}'
  labels:
    app: '{{ .Metadata.metadata.app_name }}'
spec:
  type: ClusterIP
#  type: LoadBalancer
#  loadBalancerIP: <nebula_overlay_ip>
  ports:
  - name: server
    protocol: TCP
    port: {{ .Basic_Configs.networking.ANYLOG_SERVER_PORT }}
    targetPort: {{ .Basic_Configs.networking.ANYLOG_SERVER_PORT }}
  - name: rest
    protocol: TCP
    appProtocol: http
    port: {{ .Values.node_configs.networking.ANYLOG_REST_PORT }}
    targetPort: {{ .Values.node_configs.networking.ANYLOG_REST_PORT }}
  {{- if .Values.node_configs.networking.ANYLOG_BROKER_PORT }}
  - name: broker
    protocol: TCP
    port: {{ .Values.node_configs.networking.ANYLOG_BROKER_PORT }}
    targetPort: {{ .Values.node_configs.networking.ANYLOG_BROKER_PORT }}
  {{ end }}
  selector:
    app: '{{ .Metadata.metadata.app_name }}'
