apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.service_name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.metadata.app_name }}
  ports:
    - name: anylog-server
      protocol: TCP
      port: {{ .Values.node_configs.networking.ANYLOG_SERVER_PORT }}
      targetPort: {{ .Values.node_configs.networking.ANYLOG_SERVER_PORT }}
    - name: anylog-rest
      protocol: TCP
      port: {{ .Values.node_configs.networking.ANYLOG_REST_PORT }}
      targetPort: {{ .Values.node_configs.networking.ANYLOG_REST_PORT }}
    {{- if .Values.node_configs.networking.ANYLOG_BROKER_PORT }}
    - name: anylog-broker
      protocol: TCP
      port: {{ .Values.node_configs.networking.ANYLOG_BROKER_PORT }}
      targetPort: {{ .Values.node_configs.networking.ANYLOG_BROKER_PORT }}
    {{ end }}
