apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.service_name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.metadata.app_name }}
  ports:
    - name: anylog-server
      protocol: TCP
      port: {{ .Values.node_configs.networking.ANYLOG_SERVER_PORT }}
      targetPort: {{ .Values.node_configs.networking.ANYLOG_SERVER_PORT }}
      nodePort: {{ .Values.node_configs.networking.ANYLOG_SERVER_PORT }}
    - name: anylog-rest
      protocol: TCP
      port: {{ .Values.node_configs.networking.ANYLOG_REST_PORT }}
      targetPort: {{ .Values.node_configs.networking.ANYLOG_REST_PORT }}
      nodePort: {{ .Values.node_configs.networking.ANYLOG_REST_PORT }}

