GENERAL:
  IMAGE: postgres
  TAG: 16.0-alpine
  NAME: postgres

NETWORK_CONFIGS:
  NETWORK_MODE: ports
  PORTS:
    - 5432

ENV_VARS:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: passwd
  POSTGRES_INITDB_ARGS: "--auth=md5"

VOLUMES:
  pgdata: /var/lib/postgresql/data