apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{ .Values.metadata.namespace }}'
  name: '{{ .Values.metadata.deployment_name }}'
  labels:
    app: '{{ .Values.metadata.app_name }}'
spec:
  replicas: {{ .Values.metadata.replicas }}
  selector:
    matchLabels:
      app: '{{ .Values.metadata.app_name }}'
  template:
    metadata:
      labels:
        app: '{{ .Values.metadata.app_name }}'
    spec:
      containers:
      - name: '{{ .Values.metadata.app_name }}'
        image: '{{ .Values.image.repository }}'
        ports:
        - containerPort: {{ .Values.node_configs.nginx.nginx_port }}
