apiVersion: v1
kind: Service
metadata:
  namespace: '{{ .Values.metadata.namespace }}'
  name: '{{ .Values.metadata.service_name }}'
  labels:
    app: '{{ .Values.metadata.app_name }}'
spec:
  type: NodePort
  ports:
  - name: nginx
    protocol: TCP
    port: {{ .Values.node_configs.nginx.nginx_port }}
    targetPort: {{ .Values.node_configs.nginx.nginx_port }}
    nodePort: {{ .Values.node_configs.nginx.node_port }}
  selector:
    app: '{{ .Values.metadata.app_name }}'
